server:
  port: 8088
spring:
  profiles:
    active: subversion
  application:
    name: clound-config-server
  cloud:
    config:
      label: config
      enabled: true
      server:
        svn:
          uri: https://127.0.0.1:443/svn/one
          username: lizehao
          password: 123456
#svn://127.0.0.1:3690/one